contact_links:
  - name: GitHub Discussions
    url: "https://github.com/themadorg/madmail/discussions"
    about: "Please use GitHub Discussions for questions and support. We do not have an IRC channel."
  - name: Project Priorities
    url: "https://github.com/orgs/themadorg/projects/1"
    about: "Check our Project Board for current priorities and tasks."
  - name: Delta Chat Support Forum
    url: "https://support.delta.chat/categories"
    about: "Official Delta Chat community forum for all users."
